### ISSUE TITLE
Returns error when trying to run ML.Alpha(187 ,c(3151,2350,30752), lev=0.9)[1:3] 

### ISSUE THREAD

**Issue by Haansololfp** [kpmainali/CooccurrenceAffinity#1]
Hi, I got an error like this when trying to run ML.Alpha(187 ,c(3151,2350,30752), lev=0.9)[1:3]. Do you have any ideas about what might went wrong? Thanks!
![Screenshot from 2022-01-28 12-13-13](https://user-images.githubusercontent.com/60671053/151591605-430613ff-c9ff-4bec-bd1a-e2c20886fe0e.png)

**Comment by kpmainali** [comment]
Hello, the problem arises only when the alpha values tried as part of our numerical search for MLEs and CIs are more extreme than abs(10). Please adjust the "scal" parameter by replacing the supplied value of log(2*N^2) by 10, and the function works. We have justifiable reasons for the capping. Our package utilizes another package for some of the fundamental computations and so the limit to our functions are determined upstream. We will revise our package to reflect these changes in a few days.

**Comment by Haansololfp** [comment]
Thank you for your reply! Do you mean that instead of running

> AlphInts(187 ,c(3151,2350,30752),lev=0.9, scal = 10)

I should try

>  AlphInts(187 ,c(3151,2350,30752),lev=0.9, scal = 10)?

I tried to run with the new line and it still gives me the same error. Am I understanding it wrong?

**Comment by kpmainali** [comment]
Okay, in that case, it seems I have already updated other parts of our package and so it is behaving well at my end. I plan to update the package in GibHub by the end of this week if not sooner. Will let you know once I am able to do so.

**Comment by kpmainali** [comment]
Hello, have you tested the updated package? Do you still see the errors?

**Comment by kpmainali** [comment]
The problem has been resolved and I am closing this thread.
